name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: isharasaranga
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg

          # 🎨 Snake & dot colors
          color_snake: "#1E3A8A"     # main snake (dark blue)
          color_dots: "#38BDF8,#2563EB,#FACC15,#F43F5E" 
          # sky blue, deep blue, yellow, pink squares
          color_background: "transparent"

      - name: Deploy Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
